# Generated by Django 5.2.7 on 2025-11-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_taggs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='taggs',
            new_name='tags',
        ),
    ]
